// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rengifo_Alexander.Data;

#nullable disable

namespace Rengifo_Alexander.Migrations
{
    [DbContext(typeof(Rengifo_AlexanderContext))]
    [Migration("20240423035446_Summit1")]
    partial class Summit1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rengifo_Alexander.Models.ARengifo", b =>
                {
                    b.Property<int>("idEst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEst"));

                    b.Property<bool?>("Beca")
                        .HasColumnType("boolean");

                    b.Property<int?>("carreraEstidCarrea")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("dateInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nameEst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("promGeneral")
                        .HasColumnType("double precision");

                    b.Property<int>("yearEst")
                        .HasColumnType("integer");

                    b.HasKey("idEst");

                    b.HasIndex("carreraEstidCarrea");

                    b.ToTable("ARengifo");
                });

            modelBuilder.Entity("Rengifo_Alexander.Models.Carrera", b =>
                {
                    b.Property<int>("idCarrea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCarrea"));

                    b.Property<string>("campus")
                        .HasColumnType("text");

                    b.Property<string>("nombre_carrera")
                        .HasColumnType("text");

                    b.Property<int?>("numero_semestres")
                        .HasColumnType("integer");

                    b.HasKey("idCarrea");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("Rengifo_Alexander.Models.ARengifo", b =>
                {
                    b.HasOne("Rengifo_Alexander.Models.Carrera", "carreraEst")
                        .WithMany()
                        .HasForeignKey("carreraEstidCarrea");

                    b.Navigation("carreraEst");
                });
#pragma warning restore 612, 618
        }
    }
}
